### ISSUE TITLE
Micropython with AT commands via UART

### ISSUE THREAD

**Issue by chalei** [Seeed-Studio/SSCMA-Micro#79]
Hello there,

I am trying to use the grove vision AI v2 with micropython.

I can already establish the AT commands via UART interface using the Xiao ESP32S3 with this code:
```
import machine
import time
import json

uart = machine.UART(1, baudrate=921600, tx=43, rx=44)

def send_at_command(command, timeout=2000):
    uart.write(command + '\r\n')  # Send command with CRLF ending
    time.sleep_ms(timeout)  # Wait for the response (adjust timeout as needed)
    response = uart.read().decode('utf-16')  # Read the response from the device
    print('Response:', response)
    return response if response else b'No response'


while True:
    send_at_command('AT+INVOKE=1,0,1')

```

the AT commands works fine but when I try the Invoke command it seems there are some inferencing result that is missing.
when there are no object detected I got this result:

**{"type": 0, "name": "INVOKE", "code": 0, "data": {"model": {"id": 1, "type": 0, "address": 4194304, "size": 0}, "algorithm": {"type": 3, "categroy": 1, "input_from": 1, "config": {"tscore": 62, "tiou": 57}}, "sensor": {"id": 1, "type": 1, "state": 1, "opt_id": 1, "opt_detail": "480x480 Auto"}}}
{"type": 1, "name": "INVOKE", "code": 0, "data": {"count": 1, "perf": [7, 76, 0], "boxes": [], "resolution": [480, 480]}}**

but when it is detected an object the result are like this:

**{"type": 0, "name": "INVOKE", "code": 0, "data": {"model": {"id": 1, "type": 0, "address": 4194304, "size": 0}, "algorithm": {"type": 3, "categroy": 1, "input_from": 1, "config": {"tscore": 62, "tiou": 57}}, "sensor": {"id": 1, "type": 1, "state": 1, "opt_id": 1, "opt_detail": "480x480 Auto"}}}
ution": [480, 480]}}**

it seems there some missing data when it is detected an object because when I try to convert the result into json format I got an error.
can you point out what I did wrong here. My goal is to get the inferencing result like the arduino example but using micropython.

Thank You
Best Regards
Hendra

**Comment by chalei** [comment]
Wow you're right, using the same method that you share I add an equivalent micropython script like this:

`uart.init(baudrate=921600, rxbuf=32 * 1024)`

The full code looks like this

```
import machine
import time
import json

uart = machine.UART(1, baudrate=921600, tx=43, rx=44)
uart.init(baudrate=921600, rxbuf=32 * 1024)

def send_at_command(command, timeout=2000):
    uart.write(command + '\r\n')  # Send command with CRLF ending
    time.sleep_ms(timeout)  # Wait for the response (adjust timeout as needed)
    response = uart.read().decode('utf-16')  # Read the response from the device
    print('Response:', response)
    return response if response else b'No response'


while True:
    send_at_command('AT+INVOKE=1,0,1')
```


Now I got the full inference result:
**{"type": 0, "name": "INVOKE", "code": 0, "data": {"model": {"id": 1, "type": 0, "address": 4194304, "size": 0}, "algorithm": {"type": 3, "categroy": 1, "input_from": 1, "config": {"tscore": 62, "tiou": 57}}, "sensor": {"id": 1, "type": 1, "state": 1, "opt_id": 1, "opt_detail": "480x480 Auto"}}}
{"type": 1, "name": "INVOKE", "code": 0, "data": {"count": 1, "perf": [7, 76, 0], "boxes": [[224, 313, 392, 355, 87, 0]], "resolution": [480, 480]}}**


now I just need to figure out how to convert the result into json format.
Thank You very much for the  help

**Comment by andyg2** [comment]
> now I just need to figure out how to convert the result into json format.

You've received 2 json objects - they will usually be separated by a new line character or some other delimiter. Parsing each one separately makes it a lot easier to decode.
